### ISSUE TITLE
condividere progetto unity su git.

### ISSUE THREAD

**Issue by RufioRoss** [ProjectChain/SpaceShooter#14]
Vedi "how_to_upload_unity_proj_to_git.txt" & ".gitignore" su google drive.
Condividere la versione di unity usata (tutti devono usare quella versione altrimenti il progetto si rompe).

**Comment by RufioRoss** [comment]
come si fa ad assegnare l'issue?
ma task (o forse si chiama nota) deve essere per forza convertito in issue per poter avere piu' dettagio (labels, assignee, comments etc..)?

**Comment by Gulferamus** [comment]
aprendo l'issue puoi fare tutto: assegnarlo, mettere label eccetera. Da quello che abbiamo visto ieri queste opzioni aggiuntive sono possibili solo sugli issue, le note non hanno proprio quella finestra
