### ISSUE TITLE
Creare il sistema di movimento con WASD

### ISSUE THREAD

**Issue by Chococoin** [ProjectChain/SpaceShooter#8]
Creare il sistema di movimento con WASD perchè cosi il giocatore può moversi nell'ambiente di gioco.

**Comment by Gulferamus** [comment]
script con WASD completato. lo carico già?

**Comment by Chococoin** [comment]
> script con WASD completato. lo carico già?

Certo, Il codice dovrebbe essere sempre qui, anche se bugato. Che senzo c'è di tenerlo nascosto? Come la community potrebbe colaborare se nascondiamo il codice?
